# Association Rules mining

## using Apriori

### import required packages

In [1]:
import numpy as np
import matplotlib.pyplot as plt 
import pandas as pd
import seaborn as sns

### load the data

In [3]:
df = pd.read_csv('./movies.csv')
print(df)

              V1             V2             V3          V4     V5  \
0    Sixth Sense          LOTR1  Harry Potter1  Green Mile  LOTR2
1      Gladiator        Patriot     Braveheart         NaN    NaN
2          LOTR1          LOTR2            NaN         NaN    NaN
3      Gladiator        Patriot    Sixth Sense         NaN    NaN
4      Gladiator        Patriot    Sixth Sense         NaN    NaN
5      Gladiator        Patriot    Sixth Sense         NaN    NaN
6  Harry Potter1  Harry Potter2            NaN         NaN    NaN
7      Gladiator        Patriot            NaN         NaN    NaN
8      Gladiator        Patriot    Sixth Sense         NaN    NaN
9    Sixth Sense           LOTR      Gladiator  Green Mile    NaN

   Sixth Sense  Gladiator  LOTR1  Harry Potter1  Patriot  LOTR2  \
0            1          0      1              1        0      1
1            0          1      0              0        1      0
2            0          0      1              0        0      1
3            1          1      0              0        1      0
4            1          1      0              0        1      0
5            1          1      0              0        1      0
6            0          0      0              1        0      0
7            0          1      0              0        1      0
8            1          1      0              0        1      0
9            1          1      0              0        0      0

   Harry Potter2  LOTR  Braveheart  Green Mile
0              0     0           0           1
1              0     0           1           0
2              0     0           0           0
3              0     0           0           0
4              0     0           0           0
5              0     0           0           0
6              1     0           0           0
7              0     0           0           0
8              0     0           0           0
9              0     1           0           1

### pre-process the dataset

In [8]:
# from mlxtend.preprocessing import TransactionEncoder

# # create an encoder 
# encoder = TransactionEncoder()

# # fit the transactions
# encoder_transformed_data = encoder.fit(df).transform(df)

In [14]:
df.drop(['V1', 'V2', 'V3', 'V4', 'V5'], axis=1, inplace=True)
print(df)

   Sixth Sense  Gladiator  LOTR1  Harry Potter1  Patriot  LOTR2  \
0            1          0      1              1        0      1
1            0          1      0              0        1      0
2            0          0      1              0        0      1
3            1          1      0              0        1      0
4            1          1      0              0        1      0
5            1          1      0              0        1      0
6            0          0      0              1        0      0
7            0          1      0              0        1      0
8            1          1      0              0        1      0
9            1          1      0              0        0      0

   Harry Potter2  LOTR  Braveheart  Green Mile
0              0     0           0           1
1              0     0           1           0
2              0     0           0           0
3              0     0           0           0
4              0     0           0           0
5              0     0           0           0
6              1     0           0           0
7              0     0           0           0
8              0     0           0           0
9              0     1           0           1

In [15]:
from mlxtend.frequent_patterns import apriori

apriori (df, use_colnames=True , min_support=0.1)

    support                                           itemsets
0       0.6                                      (Sixth Sense)
1       0.7                                        (Gladiator)
2       0.2                                            (LOTR1)
3       0.2                                    (Harry Potter1)
4       0.6                                          (Patriot)
5       0.2                                            (LOTR2)
6       0.1                                    (Harry Potter2)
7       0.1                                             (LOTR)
8       0.1                                       (Braveheart)
9       0.2                                       (Green Mile)
10      0.5                           (Sixth Sense, Gladiator)
11      0.1                               (LOTR1, Sixth Sense)
12      0.1                       (Sixth Sense, Harry Potter1)
13      0.4                             (Sixth Sense, Patriot)
14      0.1                               (Sixth Sense, LOTR2)
15      0.1                                (LOTR, Sixth Sense)
16      0.2                          (Sixth Sense, Green Mile)
17      0.6                               (Gladiator, Patriot)
18      0.1                                  (LOTR, Gladiator)
19      0.1                            (Braveheart, Gladiator)
20      0.1                            (Green Mile, Gladiator)
21      0.1                             (LOTR1, Harry Potter1)
22      0.2                                     (LOTR1, LOTR2)
23      0.1                                (LOTR1, Green Mile)
24      0.1                             (LOTR2, Harry Potter1)
25      0.1                     (Harry Potter1, Harry Potter2)
26      0.1                        (Green Mile, Harry Potter1)
27      0.1                              (Braveheart, Patriot)
28      0.1                                (Green Mile, LOTR2)
29      0.1                                 (LOTR, Green Mile)
30      0.4                  (Sixth Sense, Gladiator, Patriot)
31      0.1                     (LOTR, Sixth Sense, Gladiator)
32      0.1               (Sixth Sense, Gladiator, Green Mile)
33      0.1                (LOTR1, Sixth Sense, Harry Potter1)
34      0.1                        (LOTR1, Sixth Sense, LOTR2)
35      0.1                   (LOTR1, Sixth Sense, Green Mile)
36      0.1                (Sixth Sense, LOTR2, Harry Potter1)
37      0.1           (Sixth Sense, Harry Potter1, Green Mile)
38      0.1                   (Sixth Sense, LOTR2, Green Mile)
39      0.1                    (LOTR, Sixth Sense, Green Mile)
40      0.1                   (Braveheart, Gladiator, Patriot)
41      0.1                      (LOTR, Green Mile, Gladiator)
42      0.1                      (LOTR1, LOTR2, Harry Potter1)
43      0.1                 (LOTR1, Green Mile, Harry Potter1)
44      0.1                         (LOTR1, Green Mile, LOTR2)
45      0.1                 (Green Mile, LOTR2, Harry Potter1)
46      0.1         (LOTR, Sixth Sense, Gladiator, Green Mile)
47      0.1         (LOTR1, Sixth Sense, LOTR2, Harry Potter1)
48      0.1    (LOTR1, Sixth Sense, Harry Potter1, Green Mile)
49      0.1            (LOTR1, Sixth Sense, LOTR2, Green Mile)
50      0.1    (Sixth Sense, LOTR2, Harry Potter1, Green Mile)
51      0.1          (LOTR1, Green Mile, LOTR2, Harry Potter1)
52      0.1  (Green Mile, LOTR2, LOTR1, Sixth Sense, Harry ...