# problem Statement

Que.5 - 

Implement a Decision Tree, Random Forest model to classify the animals in the zoo in to different categories.
Calculate Accuracy by confusion matrix, Calculate accuracy score, precision score, recall score, f1 score.

Dataset : Zoo.csv

NOTES : 

1. Import the dataset.
2. Find out the shape of data.
3. Find out null values in all columns.
4. Drop all the null values.

### import the require packages

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

### Load DataSet

In [2]:
df = pd.read_csv("Zoo.csv")
df.head()

,hair,feathers,eggs,milk,airborne,aquatic,predator,toothed,backbone,breathes,venomous,fins,legs,tail,domestic,catsize,type
0,1,0,0,1,0,0,1,1,1,1,0,0,4,0,0,1,1
1,1,0,0,1,0,0,0,1,1,1,0,0,4,1,0,1,1
2,0,0,1,0,0,1,1,1,1,0,0,1,0,1,0,0,4
3,1,0,0,1,0,0,1,1,1,1,0,0,4,0,0,1,1
4,1,0,0,1,0,0,1,1,1,1,0,0,4,1,0,1,1

### Perform EDA

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 101 entries, 0 to 100
Data columns (total 17 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   hair      101 non-null    int64
 1   feathers  101 non-null    int64
 2   eggs      101 non-null    int64
 3   milk      101 non-null    int64
 4   airborne  101 non-null    int64
 5   aquatic   101 non-null    int64
 6   predator  101 non-null    int64
 7   toothed   101 non-null    int64
 8   backbone  101 non-null    int64
 9   breathes  101 non-null    int64
 10  venomous  101 non-null    int64
 11  fins      101 non-null    int64
 12  legs      101 non-null    int64
 13  tail      101 non-null    int64
 14  domestic  101 non-null    int64
 15  catsize   101 non-null    int64
 16  type      101 non-null    int64
dtypes: int64(17)
memory usage: 13.5 KB

In [4]:
df.describe()

,hair,feathers,eggs,milk,airborne,aquatic,predator,toothed,backbone,breathes,venomous,fins,legs,tail,domestic,catsize,type
count,101.000000,101.000000,101.000000,101.000000,101.000000,101.000000,101.000000,101.000000,101.000000,101.000000,101.000000,101.000000,101.000000,101.000000,101.000000,101.000000,101.000000
mean,0.425743,0.198020,0.584158,0.405941,0.237624,0.356436,0.554455,0.603960,0.821782,0.792079,0.079208,0.168317,2.841584,0.742574,0.128713,0.435644,2.831683
std,0.496921,0.400495,0.495325,0.493522,0.427750,0.481335,0.499505,0.491512,0.384605,0.407844,0.271410,0.376013,2.033385,0.439397,0.336552,0.498314,2.102709
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000
25%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,0.000000,0.000000,2.000000,0.000000,0.000000,0.000000,1.000000
50%,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,1.000000,1.000000,1.000000,1.000000,0.000000,0.000000,4.000000,1.000000,0.000000,0.000000,2.000000
75%,1.000000,0.000000,1.000000,1.000000,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,0.000000,4.000000,1.000000,0.000000,1.000000,4.000000
max,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,8.000000,1.000000,1.000000,1.000000,7.000000

In [5]:
df.isna().sum()

hair        0
feathers    0
eggs        0
milk        0
airborne    0
aquatic     0
predator    0
toothed     0
backbone    0
breathes    0
venomous    0
fins        0
legs        0
tail        0
domestic    0
catsize     0
type        0
dtype: int64

In [6]:
df.shape

(101, 17)

In [7]:
df.corr()

,hair,feathers,eggs,milk,airborne,aquatic,predator,toothed,backbone,breathes,venomous,fins,legs,tail,domestic,catsize,type
hair,1.000000,-0.427851,-0.817382,0.878503,-0.198431,-0.473554,-0.154769,0.492531,0.191681,0.441149,-0.104245,-0.280313,0.394009,0.048973,0.207208,0.455020,-0.562384
feathers,-0.427851,1.000000,0.419248,-0.410761,0.656553,-0.058552,-0.104430,-0.613631,0.231403,0.254588,-0.145739,-0.223541,-0.206686,0.292569,0.031586,-0.135934,-0.197520
eggs,-0.817382,0.419248,1.000000,-0.938848,0.376646,0.376244,0.011605,-0.642150,-0.340420,-0.382777,0.098689,0.164796,-0.224918,-0.221090,-0.155610,-0.514650,0.661825
milk,0.878503,-0.410761,-0.938848,1.000000,-0.366765,-0.362613,-0.029721,0.628168,0.384958,0.423527,-0.242449,-0.156328,0.214196,0.210026,0.163928,0.574906,-0.723683
airborne,-0.198431,0.656553,0.376646,-0.366765,1.000000,-0.172638,-0.295181,-0.594311,-0.104718,0.286039,0.008528,-0.251157,0.043712,0.009482,0.063274,-0.349768,0.022677
aquatic,-0.473554,-0.058552,0.376244,-0.362613,-0.172638,1.000000,0.375978,0.053150,0.022463,-0.637506,0.087915,0.604492,-0.360638,-0.034642,-0.224308,-0.111866,0.326639
predator,-0.154769,-0.104430,0.011605,-0.029721,-0.295181,0.375978,1.000000,0.129452,0.051022,-0.262931,0.115391,0.190302,-0.099723,0.018947,-0.309794,0.144790,0.061179
toothed,0.492531,-0.613631,-0.642150,0.628168,-0.594311,0.053150,0.129452,1.000000,0.575085,-0.065690,-0.062344,0.364292,-0.193476,0.310368,0.069430,0.344010,-0.471527
backbone,0.191681,0.231403,-0.340420,0.384958,-0.104718,0.022463,0.051022,0.575085,1.000000,0.207666,-0.246611,0.209499,-0.432856,0.731762,0.101733,0.356976,-0.828845
breathes,0.441149,0.254588,-0.382777,0.423527,0.286039,-0.637506,-0.262931,-0.065690,0.207666,1.000000,-0.120752,-0.617219,0.369868,0.088952,0.124068,0.204125,-0.519308
venomous,-0.104245,-0.145739,0.098689,-0.242449,0.008528,0.087915,0.115391,-0.062344,-0.246611,-0.120752,1.000000,-0.033956,0.022964,-0.162724,-0.003252,-0.183748,0.321476
fins,-0.280313,-0.223541,0.164796,-0.156328,-0.251157,0.604492,0.190302,0.364292,0.209499,-0.617219,-0.033956,1.000000,-0.605652,0.204349,-0.093887,0.031705,0.099430
legs,0.394009,-0.206686,-0.224918,0.214196,0.043712,-0.360638,-0.099723,-0.193476,-0.432856,0.369868,0.022964,-0.605652,1.000000,-0.348295,0.073931,0.068791,0.131693
tail,0.048973,0.292569,-0.221090,0.210026,0.009482,-0.034642,0.018947,0.310368,0.731762,0.088952,-0.162724,0.204349,-0.348295,1.000000,0.023434,0.243277,-0.631830
domestic,0.207208,0.031586,-0.155610,0.163928,0.063274,-0.224308,-0.309794,0.069430,0.101733,0.124068,-0.003252,-0.093887,0.073931,0.023434,1.000000,0.020073,-0.181043
catsize,0.455020,-0.135934,-0.514650,0.574906,-0.349768,-0.111866,0.144790,0.344010,0.356976,0.204125,-0.183748,0.031705,0.068791,0.243277,0.020073,1.000000,-0.521030
type,-0.562384,-0.197520,0.661825,-0.723683,0.022677,0.326639,0.061179,-0.471527,-0.828845,-0.519308,0.321476,0.099430,0.131693,-0.631830,-0.181043,-0.521030,1.000000

In [8]:
df.columns

Index(['hair', 'feathers', 'eggs', 'milk', 'airborne', 'aquatic', 'predator',
       'toothed', 'backbone', 'breathes', 'venomous', 'fins', 'legs', 'tail',
       'domestic', 'catsize', 'type'],
      dtype='object')

### Split the dataset into x and y

In [9]:
x = df[['hair','eggs', 'milk','aquatic','toothed', 'backbone', 'breathes', 'venomous', 'tail', 'catsize']]
print(x.head())
y = df['type']
y.head()

   hair  eggs  milk  aquatic  toothed  backbone  breathes  venomous  tail  \
0     1     0     1        0        1         1         1         0     0
1     1     0     1        0        1         1         1         0     1
2     0     1     0        1        1         1         0         0     1
3     1     0     1        0        1         1         1         0     0
4     1     0     1        0        1         1         1         0     1

   catsize
0        1
1        1
2        0
3        1
4        1

0    1
1    1
2    4
3    1
4    1
Name: type, dtype: int64

### Split the model into Training and Testing dataset

In [10]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, train_size= 0.75, random_state=1348)

## Built the Logistic Regression

In [11]:
def model_LG():
    from sklearn.linear_model import LogisticRegressionCV

    model_lg = LogisticRegressionCV().fit(x_train, y_train)
    return model_lg

## Built the KNN model

In [12]:
def model_KNN():
    from sklearn.neighbors import KNeighborsClassifier
    model_knn = KNeighborsClassifier(n_neighbors=  3).fit(x_train, y_train)
    return model_knn

## Built the SVM model

In [13]:
def model_SVM():
    from sklearn.svm import SVC
    # c increases from 1 to 12 accuracy increasee
    model_svm = SVC(C=8,gamma='auto').fit(x_train, y_train)
    return model_svm

## Built the model for Naive Bayes

In [14]:
def model_NB():
    from sklearn.naive_bayes import GaussianNB
    model_nb = GaussianNB().fit(x_train, y_train)
    return model_nb

## Built the model for Decision Tree

In [15]:
def model_DT():
    from sklearn.tree import DecisionTreeClassifier

    model_dt = DecisionTreeClassifier(max_depth=30).fit(x_train, y_train)
    return model_dt

## Built the model for Random Forest

In [16]:
def model_Rand_forest():
    from sklearn.ensemble import RandomForestClassifier

    model_rf= RandomForestClassifier().fit(x_train, y_train)
    return model_rf

In [17]:

def model_evaluate(model, model_name):
    from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score,f1_score
    
    
    Accuracy = accuracy_score(y_test, model.predict(x_test))
    Precision = precision_score(y_test, model.predict(x_test),average='macro')
    Recall = recall_score(y_test, model.predict(x_test),average='macro')
    f1_Score = f1_score(y_test, model.predict(x_test),average='macro')

    return model_name,Accuracy,Precision,Recall,f1_Score

In [18]:
models = [(model_LG(),"LogisticRegression",(0,0)),(model_KNN(), "KNeighborsClassifier",(0,1)),
          (model_NB(),"Naive Bayes",(1,0)),(model_SVM(),"Support Vector Machine",(1,1)),
          (model_DT(),"DecisionTreeClassifier",(2,0)),(model_Rand_forest(),"RandomForest",(2,1))]

/home/sunbeam/anaconda3/lib/python3.11/site-packages/sklearn/model_selection/_split.py:737: UserWarning: The least populated class in y has only 3 members, which is less than n_splits=5.
  warnings.warn(
/home/sunbeam/anaconda3/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/home/sunbeam/anaconda3/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/home/sunbeam/anaconda3/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

## Model Evaluation

In [19]:
Results = []
for model,model_name,_ in models:
    Results.append(model_evaluate(model, model_name))

In [20]:
df1 = pd.DataFrame(Results,columns=['Algorithm','Accuracy', 'Precision', 'Recall', 'F1_Score'])
df1

                Algorithm  Accuracy  Precision    Recall  F1_Score
0      LogisticRegression  0.923077   0.933333  0.888889  0.875000
1    KNeighborsClassifier  0.923077   0.933333  0.888889  0.875000
2             Naive Bayes  0.961538   0.966667  0.986111  0.974235
3  Support Vector Machine  0.961538   0.966667  0.986111  0.974235
4  DecisionTreeClassifier  1.000000   1.000000  1.000000  1.000000
5            RandomForest  1.000000   1.000000  1.000000  1.000000